# Generated by Django 5.1 on 2024-09-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaManutenção',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('TVM', 'Trocar a válvula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento'), ('TF', 'Troca de freios'), ('TB', 'Troca de bateria'), ('TPF', 'Troca de pastilhas de freio'), ('A', 'Alinhamento'), ('TA', 'Troca de amortecedores'), ('TFA', 'Troca de filtro de ar'), ('TFO', 'Troca de filtro de óleo'), ('RCC', 'Reparar caixa de câmbio'), ('TCD', 'Troca de correia de distribuição'), ('RS', 'Reparar suspensão'), ('TBU', 'Troca de velas de ignição'), ('TFC', 'Troca de filtro de combustível')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocolo', models.CharField(blank=True, max_length=32, null=True)),
                ('categoria_manutencao', models.ManyToManyField(to='servicos.categoriamanutenção')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
